# docker-compose.simple.yml
# Minimal Docker Compose setup - just the essentials

version: '3.8'

services:
  # Backend API Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: agentic-data-explorer-api
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - API_PORT=8000
      - LOG_LEVEL=INFO
      - LOCAL_AI_HOST=ollama
      - LOCAL_AI_PORT=11434
      - MAX_QUERY_TIMEOUT=120
      - LOCAL_AI_TIMEOUT_SECONDS=90
    env_file:
      - .env
    depends_on:
      - ollama
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - agentic-network

  # Streamlit Frontend Service
  frontend:
    build:
      context: ./frontend/streamlit
      dockerfile: Dockerfile
    container_name: agentic-data-explorer-frontend
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://api:8000/api/v1
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_PORT=8501
    depends_on:
      - api
    volumes:
      - ./frontend/streamlit:/app
    restart: unless-stopped
    networks:
      - agentic-network

  # Ollama AI Service
  ollama:
    image: ollama/ollama:latest
    container_name: agentic-data-explorer-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_KEEP_ALIVE=24h
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 120s
    networks:
      - agentic-network
    # Uncomment for GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

volumes:
  ollama_data:
    driver: local

networks:
  agentic-network:
    driver: bridge