name: agentic_data_explorer

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - pandas>=2.0.0
  - numpy>=1.24.0
  - sqlalchemy>=2.0.0
  - fastapi>=0.104.0
  - uvicorn>=0.24.0
  - pytest>=7.4.0
  - requests>=2.31.0
  - python-dotenv>=1.0.0
  - pip
  - pip:
    - snowflake-connector-python>=3.0.0
    - snowflake-sqlalchemy>=1.5.0
    - langchain>=0.1.0
    - langchain-community>=0.0.10
    - ollama>=0.1.0
    - pydantic>=2.5.0
    - streamlit>=1.28.0
    - dbt-snowflake>=1.6.0
    - plotly>=5.17.0
    - transformers>=4.30.0
    - torch>=2.0.0